version: "3"

services:
  redis:
    image: redis:7.0.11-alpine
    env_file:
      - .env
    restart: on-failure

  celery:
    build: 
      context: .
    command: 
      - ./commands/start_celery.sh
    restart: always
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - redis
      - backend

  celerybeat:
    build: 
      context: .
    command:
      - ./commands/start_celerybeat.sh
    restart: always
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - redis

  backend:
    build: 
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
