# Generated by Django 4.2.7 on 2024-04-25 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            (
                                "individual_1_month",
                                "Індивідуальне членство на 1 місяць",
                            ),
                            ("individual_1_year", "Індивідуальне членство на 1 рік"),
                            ("family_1_month", "Сімейне членство на 1 місяць"),
                            ("family_1_year", "Сімейне членство на 1 рік"),
                        ],
                        max_length=50,
                        verbose_name="Тип підписка",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Ціна"),
                ),
                (
                    "start_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата початку підписки"),
                ),
                ("end_date", models.DateField(verbose_name="Дата закінчення підписки")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Користувач",
                    ),
                ),
            ],
        ),
    ]
