# Generated by Django 4.2.7 on 2024-04-25 12:09

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Ім'я та Прізвище"),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Номер телефону"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            (
                                "service_info_request",
                                "Запит інформації про послуги Amodius",
                            ),
                            ("partnership", "Співпраця/партнерство з Amodius"),
                            (
                                "communication_department",
                                "Запит до відділу комунікацій/преси",
                            ),
                            ("other", "Інше"),
                        ],
                        max_length=50,
                        verbose_name="Тема",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Коментарій")),
            ],
        ),
    ]
